doc-warnings: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
  - django
  - celery
  - flask
autodetect: true
ignore-paths:
  - docs
  - mypackage/vendor
  - parted
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
  - part*
  - count
  - coverage.xml
  - .*
python-targets:
  - 2